# -*- coding: utf-8 -*-
"""TwitterMiniProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yDI8tou3Jsmhhvrn3xjh8kCaK_-oH_cG
"""

pip install pandas textblob



import pandas as pd
from textblob import TextBlob

# Load the CSV file
df = pd.read_csv('annotations - annotation.csv')  # Replace 'your_file.csv' with your CSV file path

# Function to perform sentiment analysis and return the sentiment label
def analyze_sentiment(text):
    if isinstance(text, str):
        analysis = TextBlob(text)
        # Assign sentiment labels based on polarity
        if analysis.sentiment.polarity > 0:
            return 'Positive'
        elif analysis.sentiment.polarity == 0:
            return 'Neutral'
        else:
            return 'Negative'
    else:
        return 'No reply'  # Handle missing or non-string values

# Apply sentiment analysis for the original text and create a new column for the results
df['Tweet Sentiment'] = df['Text'].apply(analyze_sentiment)  # Replace 'Text' with the actual column name

# Apply sentiment analysis for the replies and create a new column for the results
df['Reply Sentiment'] = df['Reply'].apply(analyze_sentiment)  # Replace 'Reply' with the actual column name for replies

# Save the DataFrame back to a new CSV file
df.to_csv('output_file.csv', index=False)  # Replace 'output_file.csv' with the desired output file path